version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: realworld-docker-demo-frontend
    command: serve -s build -l 3000

  api:
    build: ./api
    container_name: realworld-docker-demo-api
    command: npm run start
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db

  auth:
    build: ./auth
    container_name: realworld-docker-demo-auth
    command: npm run start
    environment:
      - PORT=3002
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - auth_db

  nginx:
    image: nginx:stable-alpine
    container_name: realworld-docker-demo-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
      - auth_db

  api_db:
    image: mongo:latest
    container_name: realworld-docker-demo-api-db
    volumes:
      - mongodb_api:/data/db


  auth_db:
    image: mongo:latest
    container_name: realworld-docker-demo-auth-db
    volumes:
      - mongodb_auth:/data/db


volumes:
  mongodb_api:
  mongodb_auth: